repos:
- repo: local
  hooks:
    - id: ruff lint
      name: ruff lint
      entry: ruff check
      language: system
      types_or: [ python, pyi, jupyter ]
      args: [ --fix, --exclude=mock_data ]
    - id: ruff format
      name: ruff format
      entry: ruff format
      language: system
      types_or: [ python, pyi, jupyter ]
      args: [ --exclude=mock_data ]
    - id: pytest-check
      name: pytest-check
      entry: pytest -v --cov=src --cov-report term-missing
      language: system
      pass_filenames: false
      always_run: true
    - id: repo_map
      name: repo_map
      entry: python -m repo_map . ./docs/README.md --allowed-extensions .py .yaml .toml .md
      language: system

